### ISSUE TITLE
run.bat is erring

### ISSUE THREAD

**Issue by Weepingthrush** [tungdo0602/Discord-Token-Cracker#12]
When run.bat is run, I receive the following error.

Traceback (most recent call last):
  File "C:\path\main.py", line 32, in <module>
    data = json.load(config_file)
  File "C:\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
Press any key to continue . . .

Any idea what this is? Thanks!

**Comment by Weepingthrush** [comment]
Nevermind, got it working by removing the try and except commands!

**Comment by tungdo0602** [comment]
> Nevermind, got it working by removing the try and except commands!

nah i think you forgot to generate the config
